name: nilaway
on:
  push:
    branches:
    tags:
  pull_request:
    
permissions:
  contents: read

jobs:
  nilaway:
    name: nilaway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      - name: nilaway
        run: |
          go install go.uber.org/nilaway/cmd/nilaway@latest
          nilaway -exclude-errors-in-files "vendor/" .
