# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Create Release

on:
  workflow_dispatch:
    inputs:
        version-tag:
            description: "Tag of the version, e.g. v0.1"
            required: true
            type: string



jobs:

  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    env:
      VERSION: ${{ inputs.version-tag }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: bash build.sh
      
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: bin/*
        draft: true
        tag: ${{ inputs.version-tag }}
